"use client";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import { useEffect, useState } from "react";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const [showBanner, setShowBanner] = useState(false);

  useEffect(() => {
    if (typeof window !== "undefined") {
      setShowBanner(!localStorage.getItem("cookieConsent"));
    }
  }, []);

  const acceptCookies = () => {
    localStorage.setItem("cookieConsent", "true");
    setShowBanner(false);
  };

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Navbar />
        {children}
        <footer className="w-full text-center text-[10px] text-white/40 py-2 select-none pointer-events-none">
          © CorkscrewSoftware 2025
        </footer>
        {showBanner && (
          <div className="fixed bottom-0 left-0 w-full bg-teal-700 text-white p-4 flex flex-col sm:flex-row items-center justify-center gap-4 z-50 shadow-lg">
            <span className="text-sm">
              This site uses cookies for basic analytics and to enhance your experience. By using this site, you agree to our <a href="/privacy" className="underline text-white font-semibold">Privacy Policy</a>.
            </span>
            <button
              className="bg-white text-teal-700 font-bold px-4 py-2 rounded hover:bg-teal-100 transition-colors"
              onClick={acceptCookies}
            >
              Accept
            </button>
          </div>
        )}
      </body>
    </html>
  );
}
